config/routes.rb
Rails.application.routes.draw do

  root to: 'contacts#index'

  get '/index' => 'contacts#index'

  get '/get_token' => 'contacts#get_tokens'

  get '/oauth' => 'contacts#oauth'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :set_content_fetcher

  private

  def set_content_fetcher
    @fetcher ||= GoogleContactFetcher.new
  end

end

app/controllers/contacts_controller.rb
require "#{Rails.root}/lib/src/google_contact_fetcher"

class ContactsController < ApplicationController

  after_action :set_tokens, only: :get_tokens

  def index
    @page = (params[:page] || 1).to_i - 1
    @contacts = if session[:access_token]
                  @fetcher.access_token = session[:access_token]
                  @fetcher.fetch_contacts.in_groups_of(30, false)
                else
                  []
                end
  end

  def get_tokens
    if params[:code]
      @fetcher.code = params[:code]
      @fetcher.get_tokens
    end
    redirect_to root_path
  end

  def oauth
    redirect_to(@fetcher.auth.authorization_uri.to_s)
  end

  private

  def set_tokens
    session[:refresh_token] = @fetcher.refresh_token
    session[:access_token] = @fetcher.access_token
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/get.html.erb
<h1>Contacts#get</h1>
<p>Find me in app/views/contacts/get.html.erb</p>

app/views/contacts/index.html.erb
<h1>Contacts from Google Contacts</h1>

<% if @contacts.present? %>
  <table>
    <% @contacts[@page].each do |contact| %>
      <tr>
        <td><%= contact[0] %></td>
        <td><%= contact[1] %></td>
      </tr>
    <% end %>
  </table>

  <ul>
    <% (1..@contacts.length).each do |page| %>
      <li>
        <%= link_to page, root_path({page: page}) %>
      </li>
    <% end %>
  </ul>
<% else %>
    <%= link_to "Please show my contacts", oauth_path %>
    <br />
    <small>You need a Google Account.</small>
<% end %>

app/views/contacts/oauth.html.erb
<h1>Contacts#oauth</h1>
<p>Find me in app/views/contacts/oauth.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GetContacts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <style type="text/css" media="all">
      ul li {
        display: inline-block;
        float: left;
        margin: 0 5px;
      }
    </style>
  </head>

  <body>
    <%= yield %>
  </body>
</html>